"""
Builds the automated annotated PDF report the SIH26038 brief's
Explainability Module asks for ("automated annotated reports -- enabling
ophthalmologist validation in under 30 seconds for a human-in-the-loop
workflow"). Takes the SAME JSON dict main.py's /predict already returns
(the frontend already holds this in state after a prediction, so /report
just re-renders it as a PDF -- no re-inference, no MATLAB re-run) and lays
it out as a single-page, scan-in-30-seconds clinical summary: grade +
referable decision + recommendation up top (the thing a reviewer needs
first), the three image views side by side, then a structural-findings
table with the validated candidates and the lower-confidence ones (hemorrhage
type, neovascularization) visually separated -- never presented as equally
certain, matching the same "candidate, not confirmed finding" framing used
throughout the MATLAB segmentation module and the frontend's
ResultExplanation panel.

Deliberately NOT a diagnosis document: every page carries an explicit
human-in-the-loop disclaimer, and low-confidence structural signals are
labeled as such rather than folded into the main findings table.
"""
import base64
import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_STYLES = getSampleStyleSheet()

_TITLE = ParagraphStyle(
    "NetraTitle", parent=_STYLES["Title"], fontSize=18, spaceAfter=2, textColor=colors.HexColor("#0F1B2D")
)
_SUBTITLE = ParagraphStyle(
    "NetraSubtitle", parent=_STYLES["Normal"], fontSize=9, textColor=colors.HexColor("#6B7280"), spaceAfter=10
)
_SECTION = ParagraphStyle(
    "NetraSection", parent=_STYLES["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4,
    textColor=colors.HexColor("#0F1B2D"),
)
_BODY = ParagraphStyle("NetraBody", parent=_STYLES["Normal"], fontSize=10, leading=14)
_SMALL = ParagraphStyle("NetraSmall", parent=_STYLES["Normal"], fontSize=8, textColor=colors.HexColor("#6B7280"), leading=11)
_DISCLAIMER = ParagraphStyle(
    "NetraDisclaimer", parent=_STYLES["Normal"], fontSize=8, textColor=colors.HexColor("#8A4B12"),
    backColor=colors.HexColor("#FFF6E8"), borderPadding=6, leading=11,
)

_ACCENT = colors.HexColor("#E85D3D")
_TRUST = colors.HexColor("#6F9285")
_LINE = colors.HexColor("#E4E1D8")


def _b64_to_reportlab_image(b64_str: str, width_mm: float) -> Image:
    raw = base64.b64decode(b64_str)
    buf = io.BytesIO(raw)
    img = Image(buf)
    aspect = img.imageHeight / float(img.imageWidth)
    img.drawWidth = width_mm * mm
    img.drawHeight = width_mm * mm * aspect
    return img


def _findings_table(rows, header):
    data = [header] + rows
    t = Table(data, hAlign="LEFT", colWidths=[75 * mm, 30 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F1B2D")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F4EE")]),
        ("GRID", (0, 0), (-1, -1), 0.5, _LINE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def build_pdf_report(result: dict, source_filename: str | None = None) -> bytes:
    """RESULT: the dict main.py's /predict returns (as JSON, so already
    plain Python types). Returns raw PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=16 * mm, bottomMargin=14 * mm, leftMargin=16 * mm, rightMargin=16 * mm,
        title="Netra DR Screening Report",
    )
    story = []

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph("Netra — Diabetic Retinopathy Screening Report", _TITLE))
    subtitle = f"Generated {generated_at}"
    if source_filename:
        subtitle += f" · Source image: {source_filename}"
    story.append(Paragraph(subtitle, _SUBTITLE))

    story.append(Paragraph(
        "AI-ASSISTED SCREENING OUTPUT — NOT A STANDALONE DIAGNOSIS. Generated by an "
        "automated pipeline (MATLAB image quality/structure analysis + a calibrated deep "
        "learning severity grader) for human-in-the-loop review. All candidate structural "
        "findings below are unconfirmed and require ophthalmologist verification before any "
        "clinical action is taken.",
        _DISCLAIMER,
    ))
    story.append(Spacer(1, 6))

    if not result.get("gradable", True):
        quality = result.get("quality") or {}
        story.append(Paragraph("Image Quality — Not Gradable", _SECTION))
        story.append(Paragraph(
            f"Verdict: <b>{quality.get('verdict', 'reject')}</b>", _BODY,
        ))
        reasons = quality.get("reasons") or []
        if reasons:
            story.append(Paragraph("Reasons: " + ", ".join(reasons), _BODY))
        feedback = quality.get("feedback")
        if feedback:
            story.append(Spacer(1, 4))
            story.append(Paragraph(f"Recapture guidance: {feedback}", _BODY))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "This image did not pass the Stage-1 quality gate (focus / illumination / field "
            "of view) and was not graded. No severity classification or structural analysis "
            "was produced — recapture per the guidance above and resubmit.",
            _SMALL,
        ))
        doc.build(story)
        return buf.getvalue()

    # --- Quality (pass / pass_after_enhancement / borderline) ---
    quality = result.get("quality")
    if quality:
        q_line = f"Quality verdict: <b>{quality.get('verdict')}</b>"
        if quality.get("enhanced_image_used"):
            q_line += " (adaptive enhancement applied — CLAHE + illumination normalization + denoising)"
        story.append(Paragraph(q_line, _BODY))
        story.append(Spacer(1, 6))

    # --- Headline: grade + referable decision + recommendation ---
    story.append(Paragraph("Severity Grading", _SECTION))
    grade_color = _ACCENT.hexval()[2:] if result.get("referable") else _TRUST.hexval()[2:]
    story.append(Paragraph(
        f'ICDR grade: <font color="#{grade_color}"><b>{result.get("predicted_label")}</b></font> '
        f'(level {result.get("predicted_class")} of 0–4)',
        _BODY,
    ))
    referable_word = "REFERABLE" if result.get("referable") else "not referable"
    ref_prob = result.get("referable_probability")
    ref_prob_str = f"{ref_prob * 100:.1f}%" if ref_prob is not None else "n/a"
    story.append(Paragraph(
        f'Referable-DR decision (grade ≥ 2, calibrated threshold): <b>{referable_word}</b> '
        f"(probability mass on referable classes: {ref_prob_str})",
        _BODY,
    ))
    story.append(Paragraph(f"Recommendation: {result.get('recommendation', '')}", _BODY))
    story.append(Spacer(1, 6))

    probs = result.get("probabilities") or []
    if probs:
        prob_rows = [[p["label"], f"{p['probability'] * 100:.1f}%"] for p in probs]
        story.append(_findings_table(prob_rows, ["Class", "Probability"]))
    story.append(Spacer(1, 10))

    # --- Images ---
    story.append(Paragraph("Explainability Views", _SECTION))
    img_cells = []
    labels = []
    if result.get("preprocessed_image_base64"):
        img_cells.append(_b64_to_reportlab_image(result["preprocessed_image_base64"], 52))
        labels.append("Original (preprocessed)")
    if result.get("gradcam_overlay_base64"):
        img_cells.append(_b64_to_reportlab_image(result["gradcam_overlay_base64"], 52))
        labels.append("Grad-CAM (AI focus)")
    if result.get("structures_overlay_base64"):
        img_cells.append(_b64_to_reportlab_image(result["structures_overlay_base64"], 52))
        labels.append("Structures overlay")

    if img_cells:
        img_table = Table([img_cells, [Paragraph(f"<b>{l}</b>", _SMALL) for l in labels]], hAlign="LEFT")
        img_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(img_table)
    story.append(Spacer(1, 10))

    # --- Structural findings ---
    seg = result.get("segmentation_summary")
    if seg:
        story.append(Paragraph("Structural Findings — Validated Candidates", _SECTION))
        story.append(Paragraph(
            "Optic disc/fovea localization and microaneurysm/hard exudate/haemorrhage "
            "candidate detection were validated against DRIVE/IDRiD ground truth (see "
            "matlab/segmentation/README.md). Counts below are AI-flagged CANDIDATE regions "
            "for review, not confirmed lesions.",
            _SMALL,
        ))
        story.append(Spacer(1, 4))
        main_rows = [
            ["Optic disc", "Located" if seg.get("od_confidence", 0) >= 0.7 else "Uncertain"],
            ["Fovea", "Located" if seg.get("fovea_found") else "Not found"],
            ["Microaneurysm candidates", str(seg.get("microaneurysm_candidates", 0))],
            ["Hard exudate candidates", str(seg.get("exudate_candidates", 0))],
            ["Haemorrhage candidates", str(seg.get("hemorrhage_candidates", 0))],
        ]
        story.append(_findings_table(main_rows, ["Structure", "Result"]))
        story.append(Spacer(1, 8))

        story.append(Paragraph("Early Signal — Lower Confidence", _SECTION))
        story.append(Paragraph(
            "Haemorrhage TYPE (dot/blot vs. flame-shaped) and neovascularization candidates "
            "carry materially weaker evidence than the table above: haemorrhage type has no "
            "expert-labeled ground truth to validate against, and neovascularization has been "
            "checked only directionally (candidate counts trend higher on known-PDR images "
            "than known-No-DR images on real data, p&lt;0.05) — not validated at the "
            "lesion/pixel level, because no such ground truth exists in any dataset available "
            "to this project. Treat these as leads for review, not findings.",
            _SMALL,
        ))
        story.append(Spacer(1, 4))
        low_rows = [
            ["Dot/blot haemorrhage candidates", str(seg.get("hemorrhage_dot_blot_candidates", 0))],
            ["Flame haemorrhage candidates", str(seg.get("hemorrhage_flame_candidates", 0))],
            ["Neovascularization — at disc (NVD)", str(seg.get("nvd_candidates", 0))],
            ["Neovascularization — elsewhere (NVE)", str(seg.get("nve_candidates", 0))],
        ]
        story.append(_findings_table(low_rows, ["Signal", "Result"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph(
        "Model calibration note: the referable-DR decision above uses temperature-scaled "
        "probabilities calibrated on held-out external data (Messidor-2 + IDRiD), achieving "
        "90.8% sensitivity / 88.5% specificity for referable DR on that held-out test half — "
        "see training/config.py's REFERABLE_THRESHOLD docstring for the full calibration "
        "history. This report was generated automatically by Netra; it is intended solely to "
        "accelerate — not replace — ophthalmologist review.",
        _SMALL,
    ))

    doc.build(story)
    return buf.getvalue()
